{% set name = "intensity-normalization" %}
{% set version = "3.0.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/intensity_normalization-{{ version }}.tar.gz
  sha256: efe71a01c7943990eb48ba08276e929af006a8ccd5214e4df83b8896473c9459

build:
  entry_points:
    - intensity-normalize = intensity_normalization.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - hatchling
    - pip
    - python {{ python_min }}
    - pytest-runner
    - setuptools
  run:
    - python >={{ python_min }}
    - nibabel >=5.0.0
    - numpy >=1.24.0
    - scikit-fuzzy >=0.4.2
    - scipy >=1.10.0

test:
  imports:
    - intensity_normalization
  commands:
    - pip check
    - intensity-normalize --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jcreinhold/intensity-normalization
  summary: Normalize the intensity of MR images
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://intensity-normalization.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - sarthakpati
