{% set name = "intensity-normalization" %}
{% set version = "2.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/intensity_normalization-{{ version }}.tar.gz
  sha256: b3fb6b0c8468a8b163dcd3be8afdc4f80101e20ac10070e510bebe4c276c8268

build:
  entry_points:
    - fcm-normalize = intensity_normalization.cli.fcm:fcm_main
    - kde-normalize = intensity_normalization.cli.kde:kde_main
    - lsq-normalize = intensity_normalization.cli.lsq:lsq_main
    - nyul-normalize = intensity_normalization.cli.nyul:nyul_main
    - ws-normalize = intensity_normalization.cli.whitestripe:whitestripe_main
    - zscore-normalize = intensity_normalization.cli.zscore:zscore_main
    - plot-histograms = intensity_normalization.cli.histogram:histogram_main
    - tissue-membership = intensity_normalization.cli.tissue_membership:tissue_membership_main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pytest-runner
    - setuptools
  run:
    - nibabel >=3,<4
    - numpy >=1.22,<2
    - pillow >=9.0.0
    - pydicom >=2.2.2,<3
    - pymedio >=0.2.8,<1
    - python >={{ python_min }},<3.10
    - scikit-fuzzy >=0.4.2,<1
    - scikit-image >=0.17,<1
    - scikit-learn >=0.24,<2
    - scipy >=1.5,<2
    - simpleitk >=2.1.0,<3
    - statsmodels >=0.12,<1

test:
  imports:
    - intensity_normalization
  commands:
    - pip check
    - fcm-normalize --help
    - kde-normalize --help
    - lsq-normalize --help
    - nyul-normalize --help
    - ws-normalize --help
    - zscore-normalize --help
    - plot-histograms --help
    - tissue-membership --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jcreinhold/intensity-normalization
  summary: Normalize the intensity of MR images
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://intensity-normalization.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - sarthakpati
